name: Node CI

on: [ push ]

env:
  CI: 1

jobs:
  build:
    name: CI

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm ci
        run: npm ci

      - name: npm run lint
        run: npm run lint

      - name: npm run lint (css)
        run: npm run lint:css

      - name: npm test
        run: npm test -- --watchAll=false

      - name: npm build
        run: npm run build
